#!/usr/bin/env bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge in defaults and keymaps
if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

# Start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

. "$HOME"/Projects/dotfiles/lib/environment.sh

# setxkbmap -layout us,ua,ru -option grp:lalt_lshift_toggle

nvidia-settings --load-config-only
xrandr --output DP-0 --mode 2560x1440 --rate 165.08 --auto
sleep 3 # If the monitor is in the standby mode
xrandr --output DP-4 --mode 2560x1440 --rate 165.08 --left-of DP-0 --auto

eval $(gpg-agent --daemon)
# dbus-update-activation-environment --all
eval $(gnome-keyring-daemon --start --components=secrets)

exec i3
